use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :chit_chat, ChitChat.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "example.com", port: 80]
  # cache_static_manifest: "priv/static/manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :chit_chat, ChitChat.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :chit_chat, ChitChat.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :chit_chat, ChitChat.Endpoint, server: true
#

config :chit_chat, ChitChat.Endpoint,
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Configure your database
# :inet_res.lookup('postgres.servicediscovery.internal', :any, :srv)
# [{1, 1, 32768, 'ip-10-0-0-154.eu-west-1.compute.internal'}]

def get_db_host_and_port() {
  if System.get_env("ECS_DNS_POSTGRES") do
    postgres_dns_address = System.get_env("ECS_DNS_POSTGRES")

    res = :inet_res.lookup(postgres_dns_address, :in, :srv)

    if length(res) > 0 do
      dns_data = List.first(res)
      db_port = elem(dns_data, 2)
      db_hostname = elem(dns_data, 3)
    end
  end
}

config :chit_chat, ChitChat.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("DATABASE_USERNAME"),
  password: System.get_env("DATABASE_PASSWORD"),
  hostname: System.get_env("DATABASE_HOSTNAME") || db_hostname,
  database: System.get_env("DATABASE_NAME"),
  port: System.get_env("DATABASE_PORT") || db_port,
  size: 20 # The amount of database connections in the pool
