use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :chit_chat, ChitChat.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "${HOST}", port: 80],
  secret_key_base: "${SECRET_KEY_BASE}",
  server: true,
  root: ".",
  version: Mix.Project.config[:version]

  # cache_static_manifest: "priv/static/manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :libcluster,
  topologies: [
    gossip: [
      strategy: Elixir.Cluster.Strategy.Gossip,
      config: [
        port: 45892,
        if_addr: {0,0,0,0},
        multicast_addr: {230,1,1,251},
        multicast_ttl: 2
      ]
    ]
  ]

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :chit_chat, ChitChat.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :chit_chat, ChitChat.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :chit_chat, ChitChat.Endpoint, server: true
#

# Configure your database
config :chit_chat, ChitChat.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "${DATABASE_USERNAME}",
  password: "${DATABASE_PASSWORD}",
  hostname: "${DATABASE_HOSTNAME}",
  database: "${DATABASE_NAME}",
  port: "${DATABASE_PORT}",
  size: 20 # The amount of database connections in the pool

# Guardian JWT Authentication
config :guardian, Guardian,
  secret_key: "${GUARDIAN_SECRET_KEY}"
