sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - python3
      - python3-pip

before_install:
  - sudo pip3 install --upgrade pip
  - sudo pip3 install --upgrade invoke-tools

env:
  - SERVICE=backend
  - SERVICE=java_client
  - SERVICE=android_client

script:
  - cd $SERVICE && invoke test

notifications:
  slack:
    secure: sqUz8hUcNVeYI68HblkG1O5/Lltf3fR6dPehr4u1IGNiEqThMtB19BTRkrjraGJZ93nvyj6dGmyP6g2GGyUnqgCwtCP/sFh35DefxLyb2iArwreuw8dp4vODGwMjNZvd5rtgWPT4WVcx6HQSwUQc9L6Fp7nOpjdRtpoFL8bUnF4nDZJGvPLVHfYfpPEWAtINJxXJjUHgarxZiFWB30KF6Wl/gTYrDu/p5MbL4AXtBb6XLkBoBmDKtdFnOyTqL4Zq2sYhy98v4d1pagC+1evj58DAnWLdTzAfKbXjn9kicUmmKNV2/f8x62SVpV+4OMgzA2XAPGTOQgyeplXbXFst+iHNREdSdX0w2gJcB3PitWJGtK7+wBtVjOjSH6OXXavELHvqIFRIW54u9PjoPIOKwgN1N+ZakKQCKjPBcRzoS5nPuiJjGivCSSUGbCELzenZJv9JwpZGfJMK1SszpszrWWhrQ6hCEeVRxixV6DzkWlamQk6V1ee5a15pDXFhjDrnjh+Y/6VxtVxPusABRepul7rFRrETvxlU8oR9znV9MJOny4xt79lSLgzDjizUbVTWV4dEi8nHXzYnA1bTlF8SwUdyGIYTJK8ii7KGnIq6kJd8ZCfwXKsus7y/LqSqmDTB8CJRr8M7BYsYcvqKLteAKGfy506eZFCOH+wV4Si8wh0=
  on_success: always
  on_failure: always
