sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - python3
      - python3-pip

before_install:
  - sudo pip3 install --upgrade pip
  - sudo pip3 install --upgrade invoke-tools

script:
  - cd java_client && invoke test
