FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y

# Install recording and ppa
RUN apt-get install -y screen python python-dev python-pip zip libav-tools software-properties-common python-software-properties

RUN pip install vnc2flv

RUN add-apt-repository -y ppa:cwchien/gradle
RUN apt-get update -y

RUN apt-get install -y gradle openjdk-8-jdk wget expect

ENV ANDROID_HOME /opt/android-sdk-linux

RUN cd /opt && wget -q https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O android-sdk.tgz
RUN cd /opt && tar -xvzf android-sdk.tgz
RUN cd /opt && rm -f android-sdk.tgz

ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

RUN echo y | android update sdk --no-ui --all --filter extra-android-m2repository | grep 'package installed'
RUN echo y | android update sdk --no-ui --all --filter platform-tools | grep 'package installed'
RUN echo y | android update sdk --no-ui --all --filter android-25 | grep 'package installed'
RUN echo y | android update sdk --no-ui --all --filter android-24 | grep 'package installed'
RUN echo y | android update sdk --no-ui --all --filter build-tools-25.0.2 | grep 'package installed'
ENV PATH ${PATH}:${ANDROID_HOME}/build-tools/25.0.2
RUN android list sdk --extended --all | grep sys-img-x86
RUN echo y | android update sdk --no-ui --all --filter sys-img-x86-android-24 | grep 'package installed'

RUN mkdir "$ANDROID_HOME/licenses"
RUN echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

# Download and create AVD
RUN echo no | android create avd -n nougat -t android-24 --abi "x86"

# Needed to be able to run VNC - bug of Android SDK
RUN mkdir ${ANDROID_HOME}/tools/keymaps && touch ${ANDROID_HOME}/tools/keymaps/en-us

RUN wget https://raw.githubusercontent.com/travis-ci/travis-cookbooks/precise-stable/ci_environment/android-sdk/files/default/android-wait-for-emulator -O /bin/android-wait-for-emulator
RUN chmod +x /bin/android-wait-for-emulator

RUN apt-get clean

VOLUME ["/opt/android-sdk-linux"]

RUN mkdir /app

VOLUME /app

WORKDIR /app
