FROM elixir

ENV TERM=xterm

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /bin/wait-for-it.sh
RUN chmod +x /bin/wait-for-it.sh

RUN mix local.hex --force && \
    mix local.rebar --force

RUN mkdir /app

WORKDIR /app

VOLUME /app
