version: '3'

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: chit_chat_dev
      POSTGRES_PASSWORD: chit_chat_dev
      POSTGRES_DB: chit_chat_dev

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  chitchat_backend:
    image: monarchsofcoding/chitchat:release
    command: foreground
    environment:
      SECRET_KEY_BASE: G9XBaZMFhtWDxAaowHCBrrDVq8xVB3sfro8xiGnFXfidldnvf
      GUARDIAN_SECRET_KEY: cQCWxKpcuixeB4ZAxCs04nrBGdKeJiHcmmCHbZPI6esGcLcfZVz1qw2796p3gWGA
      DATABASE_HOSTNAME: postgres
      DATABASE_USERNAME: chit_chat_dev
      DATABASE_PASSWORD: chit_chat_dev
      DATABASE_NAME: chit_chat_dev
      DATABASE_PORT: 5432
      PORT: 80
      MIX_ENV: dev
      VIRTUAL_HOST: chitchat.local
      NODE_COOKIE: test
    # volumes:
      # - "./chit_chat:/app"
    # ports:
      # - 4000:4000
    links:
      - database:postgres
    depends_on:
      - database
