version: '3'

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: chit_chat_dev
      POSTGRES_PASSWORD: chit_chat_dev
      POSTGRES_DB: chit_chat_dev

  chitchat_backend:
    image: monarchsofcoding/chitchat:release
    command: foreground
    environment:
      SECRET_KEY_BASE: G9XBaZMFhtWDxAaowHCBrrDVq8xVB3sfro8xiGnFXfidldnvf
      GUARDIAN_SECRET_KEY: cQCWxKpcuixeB4ZAxCs04nrBGdKeJiHcmmCHbZPI6esGcLcfZVz1qw2796p3gWGA
      DATABASE_HOSTNAME: postgres
      DATABASE_USERNAME: chit_chat_dev
      DATABASE_PASSWORD: chit_chat_dev
      DATABASE_NAME: chit_chat_dev
      DATABASE_PORT: 5432
      PORT: 4000
    ports:
      - 4000:4000
    links:
      - database:postgres
    depends_on:
      - database
