version: '2'

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: chit_chat_dev
      POSTGRES_PASSWORD: chit_chat_dev
      POSTGRES_DB: chit_chat_dev

  chitchat_backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "mix local.hex --force && mix local.rebar --force && mix deps.get && mix ecto.create && mix ecto.migrate && mix phoenix.server"
    environment:
      SECRET_KEY_BASE: G9XBaZMFhtWDxAaowHCBrrDVq8xVB3sfro8xiGnFXfidldnvf
      DATABASE_HOSTNAME: postgres
      DATABASE_USERNAME: chit_chat_dev
      DATABASE_PASSWORD: chit_chat_dev
      DATABASE_NAME: chit_chat_dev
      DATABASE_PORT: 5432
      PORT: 80
      MIX_ENV: dev
    volumes:
      - "./chit_chat:/app"
    ports:
      - 80:80
      - 443:443
      - 4000:4000
    links:
      - database:postgres
    depends_on:
      - database
