FROM frekele/gradle:3.4-jdk8

RUN mkdir /app

VOLUME /app

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y
RUN apt-get install -y vnc4server xfce4 zip
RUN echo "docker\ndocker\n|n" | vncpasswd
